/*
* Adéla Grichová
* GRI0073
* ZPG 2026
*/

#include "App.h"

App::App()
{
	// Initialize GLFW
	if (!glfwInit())
		exit(EXIT_FAILURE);

	Window = glfwCreateWindow(1200, 1000, "ZPG", NULL, NULL);
	if (!Window)
	{
		glfwTerminate();
		exit(EXIT_FAILURE);
	}

	glfwMakeContextCurrent(Window);
	glfwSwapInterval(1);

	// Initialize GLAD and load OpenGL function pointers
	if (!gladLoadGL((GLADloadfunc)glfwGetProcAddress))
	{
		printf("GLAD initialization failed\n");
		exit(EXIT_FAILURE);
	}

	glfwSetWindowUserPointer(Window, this);

	// Sets the key callback
	glfwSetKeyCallback(Window, KeyCallback);
	glfwSetCursorPosCallback(Window, CursorCallback);
	glfwSetMouseButtonCallback(Window, ButtonCallback);
	glfwSetWindowFocusCallback(Window, WindowFocusCallback);
	glfwSetWindowIconifyCallback(Window, WindowIconifyCallback);
	glfwSetWindowSizeCallback(Window, WindowSizeCallback);

	glfwGetFramebufferSize(Window, &Width, &Height);
	Ratio = Width / (float)Height;
	glViewport(0, 0, Width, Height);


	glMatrixMode(GL_PROJECTION);
	glLoadIdentity();
	glOrtho(-Ratio, Ratio, -1.f, 1.f, 1.f, -1.f);

	// Projection matrix : 45� Field of View, 4:3 ratio, display range : 0.1 unit <-> 100 units
	Projection = glm::perspective(45.0f, 4.0f / 3.0f, 0.01f, 100.0f);

	// Camera matrix
	View = glm::lookAt(
		glm::vec3(10, 10, 10), // Camera is at (4,3,-3), in World Space
		glm::vec3(0, 0, 0), // and looks at the origin
		glm::vec3(0, 1, 0)  // Head is up (set to 0,-1,0 to look upside-down)
	);
	// Model matrix : an identity matrix (model will be at the origin)
	ModelMatrix = glm::mat4(1.0f);


	glEnable(GL_DEPTH_TEST);//Do depth comparisons and update the depth buffer.
}

App::~App()
{
	for (Scene* s : scenes) {
		delete s;
	}

	glfwDestroyWindow(Window);
	glfwTerminate();
	exit(EXIT_SUCCESS);
}

void App::GetVersionInfo()
{
	printf("OpenGL Version: %s\n", glGetString(GL_VERSION));
	printf("Vendor %s\n", glGetString(GL_VENDOR));
	printf("Renderer %s\n", glGetString(GL_RENDERER));
	printf("GLSL %s\n", glGetString(GL_SHADING_LANGUAGE_VERSION));
	int major, minor, revision;
	glfwGetVersion(&major, &minor, &revision);
	printf("Using GLFW %i.%i.%i\n", major, minor, revision);
}

void App::Run()
{
	InitScenes();
	double lastFrameTime = glfwGetTime();

	while (!glfwWindowShouldClose(Window))
	{
		double currentTime = glfwGetTime();
		float deltaTime = static_cast<float>(currentTime - lastFrameTime);
		lastFrameTime = currentTime;

		Scene* currentScene = scenes[currentSceneIndex];

		float rotationSpeed = 1.5f; // radians per second

		// The following code was generated by AI (Source: Sonnet 5, Model: Claude Anthropic)
		if (rotateLeftPressed) {
			DrawableObject* obj = currentScene->GetSelectedObject();
			if (obj) obj->transform.angle += rotationSpeed * deltaTime;
		}
		if (rotateRightPressed) {
			DrawableObject* obj = currentScene->GetSelectedObject();
			if (obj) obj->transform.angle -= rotationSpeed * deltaTime;;
		}

		// Clear color and depth buffer
		glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
		currentScene->Draw();

		// Display the rendered frame and process events
		glfwSwapBuffers(Window);
		glfwPollEvents();
	}
}

void App::InitScenes()
{
	Scene* scene1 = new Scene();
	ShaderProgram* shader1 = scene1->AddShader("shaders/basic.vert", "shaders/basic.frag");
	Model* model1 = scene1->AddModel(triangle, sizeof(triangle) / 6, 6);
	DrawableObject* object1 = new DrawableObject(model1, shader1);
	scene1->AddObject(object1);
	scenes.push_back(scene1);

	Scene* scene2 = new Scene();
	Model* model2 = scene2->AddModel(square, sizeof(square) / 6, 6);
	DrawableObject* object2 = new DrawableObject(model2, shader1);
	scene2->AddObject(object2);
	scenes.push_back(scene2);

	Scene* scene3 = new Scene();
	Model* model3 = scene3->AddModel(sphere, sizeof(sphere) / 6, 6);
	DrawableObject* object3 = new DrawableObject(model3, shader1);
	scene3->AddObject(object3);
	scenes.push_back(scene3);

	Scene* scene4 = new Scene();
	ShaderProgram* shader2 = scene4->AddShader("shaders/basic-forest.vert", "shaders/basic.frag");
	Model* model4 = scene4->AddModel(tree, sizeof(tree) / 6, 6);
	Model* model5 = scene4->AddModel(bushes, sizeof(bushes) / 6, 6);
	for (int i = 0; i < 13; i++) {
		DrawableObject* object4 = new DrawableObject(model4, shader2);

		// The following code was generated by AI (Source: Sonnet 5, Model: Claude Anthropic)
		// Randomize the position, scale, and rotation of the trees
		object4->transform.translation.x = (i - 6) * 1.5f + ((rand() % 100) / 100.0f - 0.5f);	// random offset in the range -0.5 to 0.5
		object4->transform.translation.y = 0.0f;
		object4->transform.translation.z = (rand() % 100) / 100.0f * 4.0f - 2.0f;	// random z position in the range -2.0 to 2.0

		float randomScale = 0.7f + (rand() % 100) / 100.0f * 0.6f; // range cca 0.7 - 1.3
		object4->transform.scale = glm::vec3(randomScale);

		object4->transform.angle = (rand() % 360) * (3.14159f / 180.0f); // random angle 0-360° in radians
		object4->transform.rotationAxis = 1; // rotation around Y (tree just rotates in place, doesn't fall over)

		scene4->AddObject(object4);
	}
	for (int i = 0; i < 12; i++) {
		DrawableObject* object5 = new DrawableObject(model5, shader2);

		// The following code was generated by AI (Source: Sonnet 5, Model: Claude Anthropic)
		object5->transform.translation.x = (i - 6) * 1.5f + ((rand() % 100) / 100.0f - 0.5f);	// random offset in the range -0.5 to 0.5
		object5->transform.translation.y = 0.0f;
		object5->transform.translation.z = (rand() % 100) / 100.0f * 4.0f - 2.0f;	// random z position in the range -2.0 to 2.0

		float randomScale = 0.7f + (rand() % 100) / 100.0f * 0.6f; // range cca 0.7 - 1.3
		object5->transform.scale = glm::vec3(randomScale);

		object5->transform.angle = (rand() % 360) * (3.14159f / 180.0f); // random angle 0-360° in radians
		object5->transform.rotationAxis = 1; // rotation around Y

		scene4->AddObject(object5);
	}

	scenes.push_back(scene4);
}

void App::ErrorCallback(int error, const char* description) { fputs(description, stderr); }

void App::KeyCallback(GLFWwindow* window, int key, int scancode, int action, int mods)
{
	App* app = static_cast<App*>(glfwGetWindowUserPointer(window));

	// scene switching
	// The following code was generated by AI (Source: Sonnet 5, Model: Claude Anthropic)
	if (action == GLFW_PRESS) {
		int newIndex = -1;
		if (key == GLFW_KEY_1) newIndex = 0;
		if (key == GLFW_KEY_2) newIndex = 1;
		if (key == GLFW_KEY_3) newIndex = 2;
		if (key == GLFW_KEY_4) newIndex = 3;

		if (newIndex >= 0 && newIndex < (int)app->scenes.size())
			app->currentSceneIndex = newIndex;
	}

	if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS)
		glfwSetWindowShouldClose(window, GL_TRUE);

	// rotation - continuous while key is pressed
	if (key == GLFW_KEY_A) {
		if (action == GLFW_PRESS) app->rotateLeftPressed = true;
		if (action == GLFW_RELEASE) app->rotateLeftPressed = false;
	}
	if (key == GLFW_KEY_D) {
		if (action == GLFW_PRESS) app->rotateRightPressed = true;
		if (action == GLFW_RELEASE) app->rotateRightPressed = false;
	}

	if (key == GLFW_KEY_TAB && action == GLFW_PRESS)
		app->scenes[app->currentSceneIndex]->SelectNextObject();

	// rotation axis selection
	if (key == GLFW_KEY_X && action == GLFW_PRESS) {
		DrawableObject* obj = app->scenes[app->currentSceneIndex]->GetSelectedObject();
		if (obj) obj->transform.rotationAxis = 0;
	}
	if (key == GLFW_KEY_Y && action == GLFW_PRESS) {
		DrawableObject* obj = app->scenes[app->currentSceneIndex]->GetSelectedObject();
		if (obj) obj->transform.rotationAxis = 1;
	}
	if (key == GLFW_KEY_Z && action == GLFW_PRESS) {
		DrawableObject* obj = app->scenes[app->currentSceneIndex]->GetSelectedObject();
		if (obj) obj->transform.rotationAxis = 2;
	}

	// translation
	if (key == GLFW_KEY_LEFT && action == GLFW_PRESS) {
		DrawableObject* obj = app->scenes[app->currentSceneIndex]->GetSelectedObject();
		if (obj) obj->transform.translation.x -= 0.1f;
	}
	if (key == GLFW_KEY_RIGHT && action == GLFW_PRESS) {
		DrawableObject* obj = app->scenes[app->currentSceneIndex]->GetSelectedObject();
		if (obj) obj->transform.translation.x += 0.1f;
	}
	// scale
	if (key == GLFW_KEY_UP && action == GLFW_PRESS) {
		DrawableObject* obj = app->scenes[app->currentSceneIndex]->GetSelectedObject();
		if (obj) obj->transform.scale += glm::vec3(0.1f);
	}
	if (key == GLFW_KEY_DOWN && action == GLFW_PRESS) {
		DrawableObject* obj = app->scenes[app->currentSceneIndex]->GetSelectedObject();
		if (obj) obj->transform.scale -= glm::vec3(0.1f);
	}
}

void App::WindowFocusCallback(GLFWwindow* window, int focused) { printf("window_focus_callback \n"); }

void App::WindowIconifyCallback(GLFWwindow* window, int iconified) { printf("window_iconify_callback \n"); }

void App::WindowSizeCallback(GLFWwindow* window, int width, int height) {
	printf("resize %d, %d \n", width, height);
	glViewport(0, 0, width, height);
}

void App::CursorCallback(GLFWwindow* window, double x, double y) { printf("cursor_callback \n"); }

void App::ButtonCallback(GLFWwindow* window, int button, int action, int mode) {
	if (action == GLFW_PRESS) printf("button_callback [%d,%d,%d]\n", button, action, mode);
}
